### ISSUE TITLE
Does not work even with .nojekyll

### ISSUE THREAD

**Issue by nomeata** [s4y/gh-pages-symlink-test#10]
Unfortunately, it does not work:
- This is the real file: https://github.com/nomeata/mitschriebwiki/blob/gh-pages/data/css/toc.css
- This is the symlink: https://github.com/nomeata/mitschriebwiki/blob/gh-pages/css with content `data/css`
- This works: http://nomeata.github.io/mitschriebwiki/data/css/screen.css
- This does not work: http://nomeata.github.io/mitschriebwiki/css/screen.css
- This file is present: https://github.com/nomeata/mitschriebwiki/blob/gh-pages/.nojekyll

Any ideas?

**Comment by s4y** [comment]
It looks like symlinks have better support now (even without `.nojekyll`). Could you try again?
