### ISSUE TITLE
README.md URLs are broken due to GitHub username change

### ISSUE THREAD

**Issue by follower** [s4y/gh-pages-symlink-test#11]
The links currently refer to a user named `sidnicious`, e.g.:

*  <http://sidnicious.github.io/gh-pages-symlink-test/link.txt>

But this repository is now owned by a user named `s4y`, so correct links are:

* <http://s4y.github.io/gh-pages-symlink-test/link.txt>
* <http://s4y.github.io/gh-pages-symlink-test/target.txt>
* <http://s4y.github.io/gh-pages-symlink-test/docs/current/>
* <http://s4y.github.io/gh-pages-symlink-test/docs/hello/>

**Comment by s4y** [comment]
Fixed, thanks!
