### ISSUE TITLE
Try with a symlinked folder

### ISSUE THREAD

**Issue by fenollp** [s4y/gh-pages-symlink-test#4]
Hey,
@electrum pointed me to his symlink: https://github.com/facebook/presto/blob/gh-pages/docs/current
…and it works: http://facebook.github.io/presto/docs/current/
I am still waiting for [my own](https://github.com/fenollp/erldocs/blob/gh-pages/current/) symbolic folder [to work](http://fenollp.github.io/erldocs/current/), though.

**Comment by dandv** [comment]
@fenollp: the repo has been removed apparently, so I can't see your symlink working.

But I've put up another repo, with only a gh-pages branch, and no symlinks work whatsoever.

https://github.com/dandv/gh-pages-symlink-fail/

**Comment by fenollp** [comment]
@dandv [Try adding a `.nojekyll` file](https://github.com/isaacs/github/issues/553#issue-126873409)

**Comment by s4y** [comment]
Looks like directory symlinks work now :).
