### ISSUE TITLE
What is the rationale for requiring .nojekyll in that case?

### ISSUE THREAD

**Issue by cirosantilli** [s4y/gh-pages-symlink-test#6]
Security? Can someone point to something evil that could be done in that case?

Of course, assuming that the symlink must point into the current repository, which is imposed even if `.nojekyll` is there: https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository/

**Comment by s4y** [comment]
It looks like `.nojekyll` is no longer required. Does it work for you, too?
